In [ ]:
import numpy as np

# Create a list
a= [1,2,3,4,5]
numpy_array= np.array(a)

print (numpy_array)




In [ ]:
# two dimenstion 
b = [[10,11,12,13],[44,15,66,88],[44,85,63,98],[44,55,66,88]]
b

b_array=np.array(b)
b_array

In [ ]:
# Show the numpy array dimensions
print("Two Dimention Array",b_array.ndim)
print("Two List", numpy_array.ndim)

# Show the numpy array shape AxB
print("Array b_array Shape",b_array.shape)

# Show the numpy array size = total elements
print("Array b_array Size",b_array.size)



In [ ]:
# Access to specific element
print("Print b_array" ,b_array)
print("Access to element 2,1 opt1: ",b_array[2,1])
print("Access to element 2,1 opt2: ",b_array[1][1])

print("Access to element First Line : ",b_array[0:2][1])
print("Access to element 2,1 opt2: ",b_array[2][0:2])

In [ ]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
print("array x",X)

# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
print("array y",Y)

#ADD z= X+Y
z=X+Y
z


# Calculate the dot product

Z_product = np.dot(X,Y)
print("Z_product result z= XdotY: ",Z_product)

In [8]:
#Statistical Function
print(b_array)
max_b=b_array.max()
print("Maximum Value in the array ",max_b)

min_b_=b_array.min()
print("Minimum Value in the array ", min_b_)

mean_b_=b_array.mean()
print("MEAN Value in the array ", mean_b_)




[[10 11 12 13]
 [44 15 66 88]
 [44 85 63 98]
 [44 55 66 88]]
Maximum Value in the array  98
Minimum Value in the array  10
MEAN Value in the array  50.125


In [2]:
def f():
    return 3


def test_function():
    assert f() == 4

